PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX urb: <http://purl.archive.org/urbooks#>
PREFIX urw: <http://purl.archive.org/urwriters#>
PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX reo: <ttp://www.semanticweb.org/research-ontology/>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX org: <http://www.w3.org/ns/org#>


#java -jar sparql-anything.jar -q queries/query.sparql > output.ttl
CONSTRUCT {
    ?person a foaf:Person;
        rdfs:label ?fullName;
        reo:authorName ?reoname;
        reo:authorSurname ?reosurname;
        reo:authorGender ?reogenre;
        reo:authorNationality ?reonationality;
        reo:authorEmail ?reoemail;
        reo:UGOVID ?reougovId;
        reo:IRISID ?reoid;
        reo:orcidId ?reoorcid;
        reo:registrationNumber ?reoRegistrationNumber;
        reo:scopusID ?reoscopus;
        reo:orcidId ?reoorcid;
        reo:affiliationStart ?reoAffiliationStart;
        reo:affiliationEnd ?reoAffiliationEnd;
        dul:hasRole ?reorole;
        reo:hsaMinisterialAreaAffiliation ?reoministerialArea;
        reo:impactHistory ?reoImpactHistory;
        reo:hasCurrentAffiliation ?reoAffiliation;
        reo:hasTopic: ?reoercKeywords;
        reo:hasTopic: ?reoKeywords;
        reo:countryOfBirth: ?reoCountryOfBird;
        reo:placeOfBirth: ?reoPlaceOfBirth;
        reo:IRISTotalPubblication: ?reoIRIStotalPubblication;
        reo:ScopusTotalPubblication: ?reoScopusTotalPubblication;
        reo:WosTotalPubblication: ?reoWosTotalPubblication.
    ?reorole a dul:Role;
        skos:altLabel ?reoQualification.
    ?reoministerialArea a reo:AcademinArea;
        skos:narrower ?reoScientificArea.
    ?reoAffiliation a org:Department.
        #skos:narrower ?reoScientificArea.
} WHERE {
  SERVICE <x-sparql-anything:csv.headers=true,location=data/authors.csv> {
    []      xyz:ID-IRIS ?id;
            xyz:Nome ?name;
            xyz:Cognome ?surname;
            xyz:Genere ?genre;
            xyz:Nazionalita ?nationality;
            xyz:E-mail ?email;
            xyz:ID-UGOV ?ugovId;
            xyz:ORCID ?orcid;
            xyz:Scopus ?scopus;
            xyz:Affiliazione-Inizio ?affiliationStart;
            xyz:Affiliazione-Fine ?affiliationEnd;
            xyz:Affiliazione-Matricola ?registrationNumber;
            xyz:Ruolo ?role;
            xyz:Qualifica ?qualification;
            xyz:Struttura ?affiliation;
            xyz:Area-ministeriale ?ministerialArea;
            xyz:Gruppo-Scientifico-Disciplinare ?scientificArea;
            xyz:Impact-History ?impactHistory;
            xyz:Parole-chiave-ERC ?ercKeywords;
            xyz:Parole-chiave ?keywords;
            xyz:Nazione-di-nascita ?countryOfBird;
            xyz:Luogo-di-nascita ?placeOfBirth;
            xyz:Pubblicazioni-Totale-IRIS ?IRISTotalPubblication;
            xyz:Totale-Scopus ?ScopusTotalPubblication;
            xyz:Totale-Wos ?WosTotalPubblication;
  }
  BIND(CONCAT(STR(?name), " ", STR(?surname)) AS ?fullName)
  BIND(IRI(CONCAT(STR(reo:), LCASE(REPLACE(CONCAT(?name, "-", ?surname), " ", "-")))) AS ?person)
  BIND(IRI(CONCAT(STR(reo:), ?id )) AS ?reoid).
  BIND(IRI(CONCAT(STR(reo:), ?name )) AS ?reoname).
  BIND(IRI(CONCAT(STR(reo:), ?surname )) AS ?reosurname) .
  BIND(IRI(CONCAT(STR(reo:), ?genre )) AS ?reogenre) .
  BIND(IRI(CONCAT(STR(reo:), ?nationality )) AS ?reonationality) .
  BIND(IRI(CONCAT(STR(reo:), ?email )) AS ?reoemail) .
  BIND(IRI(CONCAT(STR(reo:), ?irisId )) AS ?reoirisId) .
  BIND(IRI(CONCAT(STR(reo:), ?ugovId )) AS ?reougovId) .
  BIND(IRI(CONCAT(STR(reo:), ?orcid )) AS ?reoorcid) .
  BIND(IRI(CONCAT(STR(reo:), ?scopus )) AS ?reoscopus) .
  BIND(IRI(CONCAT(STR(reo:), ?affiliationStart )) AS ?reoAffiliationStart) .
  BIND(IRI(CONCAT(STR(reo:), ?affiliationEnd )) AS ?reoAffiliationEnd) .
  BIND(IRI(CONCAT(STR(reo:), ?registrationNumber )) AS ?reoRegistrationNumber) .
  BIND(IRI(CONCAT(STR(reo:), ?role )) AS ?reorole) .
  BIND(IRI(CONCAT(STR(reo:), ?qualification )) AS ?reoQualification) .
  BIND(IRI(CONCAT(STR(reo:), ?ministerialArea )) AS ?reoministerialArea) .
  BIND(IRI(CONCAT(STR(reo:), ?scientificArea )) AS ?reoScientificArea) .
  BIND(IRI(CONCAT(STR(reo:), ?impactHistory )) AS ?reoImpactHistory) .
  BIND(IRI(CONCAT(STR(reo:), LCASE(REPLACE(CONCAT(?affiliation, "-department"), " ", "-")))) AS ?reoAffiliation) .
  BIND(IRI(CONCAT(STR(reo:), ?ercKeywords )) AS ?reoercKeywords) .
  BIND(IRI(CONCAT(STR(reo:), ?keywords )) AS ?reoKeywords) .
  BIND(IRI(CONCAT(STR(reo:), ?countryOfBird )) AS ?reoCountryOfBird) .
  BIND(IRI(CONCAT(STR(reo:), ?placeOfBirth )) AS ?reoPlaceOfBirth) .
  BIND(IRI(CONCAT(STR(reo:), ?IRISTotalPubblication )) AS ?reoIRIStotalPubblication) .
  BIND(IRI(CONCAT(STR(reo:), ?ScopusTotalPubblication )) AS ?reoScopustotalPubblication) .
  BIND(IRI(CONCAT(STR(reo:), ?WosTotalPubblication )) AS ?reoWostotalPubblication) .

  #BIND(IRI(CONCAT(STR(reo:), ?affiliation )) AS ?reoAffiliation) .
  #BIND(IRI(CONCAT(STR(reo:), ?affiliation )) AS ?reoAffiliation) .
  #BIND(IRI(CONCAT(STR(reo:), ?affiliation )) AS ?reoAffiliation) .

}