PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX urb: <http://purl.archive.org/urbooks#>
PREFIX urw: <http://purl.archive.org/urwriters#>
PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX reo: <http://www.semanticweb.org/liadraetta/ontologies/2024/8/research-ontology/>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prov: <http://www.w3.org/ns/prov#>

CONSTRUCT {
  ?reoid a  reo:Person;
        reo:authorName ?reoname;
        reo:authorSurname ?reosurname;
        reo:authorSurname ?reosurname;
        reo:authorGender ?reogenre;
        reo:authorNationality ?reonationality;
        reo:authorEmail ?reoemail;
        reo:UGOVID ?reougovId;
        reo:orcidId ?reoorcid;
        reo:hasRole ?reorole;


} WHERE {
  SERVICE <x-sparql-anything:csv.headers=true,location=./data/report.csv> {
    []  xyz:IRISID ?id;
            xyz:Nome ?name;
            xyz:Cognome ?surname;
            xyz:Genere ?genre;
            xyz:Nazionalita ?nationality;
            xyz:Email ?email;
            xyz:UGOVID ?ugovId;
            xyz:ORCID ?orcid;
            xyz:Ruolo ?role;
            xyz:Affiliazione ?affiliation;
            xyz:Area_ministeriale ?ministerialArea;
            xyz:Parole_chiave_ERC ?keyWordERC;
            xyz:Nazione_di_nascita ?countryOfBird;
            xyz:Totale_pubblicazioni ?totalPubblication.

  }
  BIND(IRI(CONCAT(STR(reo:), ?id )) AS ?reoid).
  BIND(IRI(CONCAT(STR(reo:), ?name )) AS ?reoname).
  BIND(IRI(CONCAT(STR(reo:), ?surname )) AS ?reosurname) .
  BIND(IRI(CONCAT(STR(reo:), ?genre )) AS ?reogenre) .
  BIND(IRI(CONCAT(STR(reo:), ?nationality )) AS ?reonationality) .
  BIND(IRI(CONCAT(STR(reo:), ?email )) AS ?reoemail) .
  BIND(IRI(CONCAT(STR(reo:), ?irisId )) AS ?reoirisId) .
  BIND(IRI(CONCAT(STR(reo:), ?ugovId )) AS ?reougovId) .
  BIND(IRI(CONCAT(STR(reo:), ?orcid )) AS ?reoorcid) .
  BIND(IRI(CONCAT(STR(reo:), ?role )) AS ?reorole) .
  BIND(IRI(CONCAT(STR(reo:), ?affiliation )) AS ?reoaffiliation) .
  BIND(IRI(CONCAT(STR(reo:), ?ministerialArea )) AS ?reoministerialArea) .
  BIND(IRI(CONCAT(STR(reo:), ?keyWordERC )) AS ?reokeyWordERC) .
  BIND(IRI(CONCAT(STR(reo:), ?countryOfBird )) AS ?reocountryOfBird) .
  BIND(IRI(CONCAT(STR(reo:), ?totalPubblication )) AS ?reototalPubblication) .
}