PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX urb: <http://purl.archive.org/urbooks#>
PREFIX urw: <http://purl.archive.org/urwriters#>
PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX reo: <http://www.semanticweb.org/research-ontology/>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX soa: <https://semopenalex.org/ontology/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX frapo: <http://purl.org/cerif/frapo/>
PREFIX soa: <https://semopenalex.org/ontology/>


#java -jar sparql-anything.jar -q queries/query.sparql > output.ttl
CONSTRUCT {
    ?work a soa:Work;
        dcterms:title ?title;
        dcterms:abstract ?abstract;
        fabio:haspPubblicationYear ?reoPubblicationYear;
        reo:hasType ?reoWorkType;
#        #capire come gestire il first author
#        reo:hasFirstAuthor ?reoFullName;
        reo:isAuthoredBy ?reoFullName, ?reoAuthors;
#        reo:numberOfAuthor ?reoAuthors;
        reo:internationalCoauthors ?reoInternationalCoauthors;
        reo:numberOfCurrentlyAffiliatedAuthors ?reoCurrentAffiliatedAuthors;
        reo:relevance ?reoRelevance;
        dcterms:language ?reolanguage;
        reo:ISSNCode ?reoISSNJournal;
        reo:DOICode ?reoDOICode;
        reo:url ?reoURL;
        soa:hasTopic ?reoKeyword, ?reoERCPanel;
        reo:conferenceName ?conference;
        reo:impactFactor ?reoImpactFactor;
        reo:openAccessType ?openAccessType;
        reo:refereeType ?refereeType;
        reo:isProducedBy ?reoProjectID.
    ?reoWorkType a reo:WorkType.
    ?reoFullName a foaf:Person.
    ?reoAuthors a foaf:Person.
    ?reoKeyword a soa:Keyword.
    ?project a frapo:Project.

} WHERE {
  SERVICE <x-sparql-anything:csv.headers=true,location=/Users/liadraetta/Desktop/community-research-ontology/data/preprocessed/pubblications_preprocessed.csv> {
    []      xyz:ID-prodotto ?id;
            xyz:Titolo ?title;
            xyz:Abstract ?abstract;
#            xyz:first-author ?firstAuthor;
            xyz:Anno-di-pubblicazione ?pubblicationYear;
            xyz:Tipologia ?workType;
            xyz:autore-nome ?authorName;
            xyz:autore-cognome ?authorSurnname;
            xyz:Curatori ?authorsNumber;
            xyz:Presenza-coautori-internazionali ?internationalCoauthors;
            xyz:curatori-attualmente-afferenti ?currentAffiliatedAuthors;
            xyz:Rilevanza ?relevance;
            xyz:Lingua ?language;
            xyz:RivistaISSN ?ISSNJournal;
            xyz:scopusDOI ?DOICode;
            xyz:URL ?url;
            xyz:Parole-chiave ?keywords;
            xyz:ERCPanel ?ERCPanel;
            xyz:convegno ?conference;
            xyz:Id-progetto ?projectID;
#            xyz:Nome-progetto ?projectName;
            xyz:Impact-factor ?impactFactor;
            xyz:open-access-type ?openAccessType;
            xyz:Tipo-di-referaggio ?refereeType;
  }

  BIND(CONCAT(STR(?name), " ", STR(?impactFactor)) AS ?reoImpactFactor) .
  BIND(CONCAT(STR(?authorName), " ", STR(?authorSurnname)) AS ?fullName) .
  BIND(IRI(CONCAT(STR(reo:), LCASE(REPLACE(CONCAT(?fullName), " ", "-")))) AS ?reoFullName).
  BIND(IRI(CONCAT(STR(reo:), LCASE(REPLACE(CONCAT(?id, "-", ?fullName), " ", "-")))) AS ?work) .
  BIND(IRI(CONCAT(STR(reo:), LCASE(REPLACE(CONCAT(?projectName, "-", ?projectID), " ", "-")))) AS ?project) .
  BIND(IRI(CONCAT(STR(reo:), ?id )) AS ?reoid).
  BIND(IRI(CONCAT(STR(reo:), ?firstAuthor )) AS ?reFirstAuthor).
  BIND(IRI(CONCAT(STR(reo:), ?pubblicationYear )) AS ?reoPubblicationYear).
  BIND(IRI(CONCAT(STR(reo:), ?workType )) AS ?reoWorkType).
  BIND(IRI(CONCAT(STR(reo:), LCASE(REPLACE(CONCAT(?authorsNumber), " ", "-")))) AS ?reoAuthors).
  BIND(IRI(CONCAT(STR(reo:), ?internationalCoauthors )) AS ?reoInternationalCoauthors).
  BIND(IRI(CONCAT(STR(reo:), LCASE(?currentAffiliatedAuthors ))) AS ?reoCurrentAffiliatedAuthors).
  BIND(IRI(CONCAT(STR(reo:), ?relevance )) AS ?reoRelevance).
  BIND(IRI(CONCAT(STR(reo:), ?language )) AS ?reolanguage).
  BIND(IRI(CONCAT(STR(reo:), ?ISSNJournal )) AS ?reoISSNJournal) .
  BIND(IRI(CONCAT(STR(reo:), ?DOICode )) AS ?reoDOICode) .
  BIND(IRI(CONCAT(STR(reo:), LCASE(REPLACE(CONCAT(?keywords), " ", "-")))) AS ?reoKeyword).
  BIND(IRI(CONCAT(STR(reo:), LCASE(REPLACE(CONCAT(?ERCPanel), " ", "-")))) AS ?reoERCPanel).
  BIND(IRI(CONCAT(STR(reo:), ?url )) AS ?reoURL) .
  BIND(IRI(CONCAT(STR(reo:), ?projectID )) AS ?reoProjectID) .
  BIND(IRI(CONCAT(STR(reo:), LCASE(REPLACE(CONCAT(?authorName, "-", ?authorSurnname), " ", "-")))) AS ?person) .
}